### ISSUE TITLE
Active class stays there when hitting enter in Firefox

### ISSUE THREAD

**Issue by rahmathm1** [NicolasCARPi/jquery_jeditable#145] opened 2015-08-06 12:29 UTC
Active class which is added when focused, is not removed when jEdittable is closed by hitting enter.

Steps to reproduce:
1. Open jEditable in Firefox
2. Click and activate on the jEditable
3. Close jEdittable by hitting Enter key
4. Observe the behavior in console
   Expected result: Active class should be removed from the element
   Actual result: Active class is not removed from the element.
   ![issue](https://cloud.githubusercontent.com/assets/2988274/9111437/ca80c45e-3c64-11e5-8a48-d3b0894a53ce.png)

**Comment by NicolasCARPi** [comment] 2017-12-19 11:42
Hello,

I cannot reproduce this behavior. Closing.

**Closed by NicolasCARPi** 2017-12-19 11:42 UTC
