### ISSUE TITLE
Select items sort by default

### ISSUE THREAD

**Issue by kkaiser1952** [NicolasCARPi/jquery_jeditable#176] opened 2018-05-31 14:13 UTC
# Description

Items in the select list will sort alphabetically instead of being listed in order of submission.

## how to reproduce

~~~javascript
$(".editable_selectTFC").editable("save.php", { 	// traffic
	    data    : '{"":"","Routine":"Routine","Welfare":"Welfare","Priority":"Priority","Emergency":"Emergency","Question":"Question","Sent":"Sent"}',
	    type    : "select",
	    tooltip : "Traffic dropdown",
	    style   : "inherit"
	 	});
~~~

## expected result

Sort by input order as seen above.

## actual result

Sort starts at Emergency and progress' alphabetically

# Environment

Browser: All
OS: All

**Comment by NicolasCARPi** [comment] 2018-05-31 14:16
So as I told you by email, this is actually a feature not a bug, but an option to control this behavior should exist.

**Comment by kkaiser1952** [comment] 2018-05-31 14:21
Did I screw up? I’m so sorry. This was the first time I ever used Github. You’re right I should have asked for it as an option.

**Comment by NicolasCARPi** [comment] 2018-05-31 14:23
It's fine don't worry ;)

**Comment by NicolasCARPi** [comment] 2018-06-20 09:19
Fixed in 2.0.5.

**Closed by NicolasCARPi** 2018-06-20 09:19 UTC
Labels: Feature request

**Comment by kkaiser1952** [comment] 2018-08-22 16:05
Hi Nicolas,

I’m having an issue with one of my edits. I have a field for comments, they may contain any kind of character. But in testing the only one that seems to be causing me issues is a single quote mark ( ‘ ). Anytime it appears in the text entered into the field it just wipes out the field and does not process the request.
I’ve tried mysql_real_escape_string() and other similar routines but none of them help. Truth is I don’t know if the problem is occurring in javascript or in PHP, all I know for sure is the text is not being entered into the field.

Below is my code for the field, can you give me a place to start on solving this issue?

$(".editC").editable("save.php", {  				// comments
		 type	   : "text",
		 placement : "top",
		 placeholder: "",
		 indicator : "Saving...",
		 tooltip   : "Comments Click to edit...",
		 style     : "inherit" 
 });


Thanks
Keith.

**Comment by NicolasCARPi** [comment] 2018-08-22 18:44
Hello,

1. Which version of PHP are you running? Do you know about PDO and prepared statements?

2. It's probably an error in your PHP code, otherwise it would be reproducible on the demo.

**Comment by NicolasCARPi** [comment] 2018-08-23 08:32
Yes you can modify the JS (see callback function), but imho you should concentrate on fixing the `'` issue you have with php. There should be no need for str_replace.
